### ISSUE TITLE
有人能帮助更新一下香港市场的假期记录么？

### ISSUE THREAD

**Issue by rainx** [rainx/cn_stock_holidays#3]
如题，可以提供pr 给我

**Comment by Naich** [comment]
http://www.sse.com.cn/services/hkexsc/home/arrange/

**Comment by Naich** [comment]
历史的难度不大找指数取一份日期就行了

**Comment by rainx** [comment]
好的，谢谢

**Comment by rongli1101** [comment]
可以把香港的假日跟新到https://raw.githubusercontent.com/rainx/cn_stock_holidays/master/cn_stock_holidays/data_hk.txt 吗？
否则hkex.sync_data()不起作用...谢谢

**Comment by rainx** [comment]
@rongli1101  @Naich  更新了一下 , 注意这里 12月24号 是休息半天的，我们这里不支持半天的假期标识，所以没有放到文件中，后面我考虑专门针对半天的情况再做处理， 大家可以试试1.3版本，看看数据是否正常，或者直接同步 data_hk.txt 查看, 这次主要修改了这个文件

**Comment by rongli1101** [comment]
多谢.
