### ISSUE TITLE
zipline 1.3 error

### ISSUE THREAD

**Issue by markqiu** [rainx/cn_stock_holidays#6]
from cn_stock_holidays.zipline.exchange_calendar_shsz import SHSZExchangeCalendar
../../.local/share/virtualenvs/stralib-Bozs3YP5/lib/python3.6/site-packages/cn_stock_holidays/zipline/__init__.py:1: in <module>
    from cn_stock_holidays.zipline.exchange_calendar_hkex import HKExchangeCalendar
../../.local/share/virtualenvs/stralib-Bozs3YP5/lib/python3.6/site-packages/cn_stock_holidays/zipline/exchange_calendar_hkex.py:9: in <module>
    from zipline.utils.calendars.trading_calendar import days_at_time, NANOS_IN_MINUTE
E   ModuleNotFoundError: No module named 'zipline.utils.calendars.trading_calendar'; 'zipline.utils.calendars' is not a package

**Comment by whuan6** [comment]
from zipline.utils.calendars.trading_calendar import days_at_time, NANOS_IN_MINUTE

请问NANOS_IN_MINUTE常量一直导入错误是怎么回事啊

**Comment by whuan6** [comment]
> 我已经改好了。

请问怎样改的啊
